# Generated by Django 5.2.10 on 2026-01-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bayi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Bayi Adı")),
                (
                    "branch_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Branch ID"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=128, verbose_name="Secret Key"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("s3_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Başarılı"),
                            ("FAILED", "Hatalı"),
                            ("PENDING", "İşleniyor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bayi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="branch_controller.bayi",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
