# Generated by Django 5.2.10 on 2026-03-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bayi Adı')),
                ('branch_id', models.CharField(max_length=50, unique=True, verbose_name='Branch ID')),
                ('secret_key', models.CharField(max_length=128, verbose_name='Secret Key')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('s3_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Başarılı'), ('FAILED', 'Hatalı'), ('PENDING', 'İşleniyor')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bayi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch_controller.bayi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('provider_id', models.CharField(blank=True, db_index=True, default='', help_text='Provider ID (örn: 01, 02)', max_length=10)),
                ('validation_date', models.DateField(blank=True, db_index=True, help_text="CSV'nin ait olduğu tarih (date= partition)", null=True)),
                ('total_rows', models.IntegerField(default=0, help_text='Toplam satır sayısı (header hariç)')),
                ('error_count', models.IntegerField(default=0, help_text='Toplam hata sayısı')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Doğruluk oranı (0.00 - 100.00)', max_digits=5)),
                ('error_summary', models.JSONField(default=dict, help_text='Hata türlerine göre gruplu detaylar')),
                ('summary_message', models.TextField(blank=True, default='', help_text='Formatlanmış özet mesaj')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bayi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch_controller.bayi')),
            ],
            options={
                'verbose_name': 'CSV Validation Özeti',
                'verbose_name_plural': 'CSV Validation Özetleri',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['bayi', 'validation_date'], name='branch_cont_bayi_id_46a362_idx'), models.Index(fields=['accuracy_rate'], name='branch_cont_accurac_4a6c59_idx'), models.Index(fields=['validation_date', 'detected_at'], name='branch_cont_validat_ff85c9_idx')],
                'unique_together': {('bayi', 'filename', 'provider_id', 'validation_date')},
            },
        ),
    ]
