# Generated by Django 5.2.10 on 2026-03-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bayi',
            options={'verbose_name_plural': 'Alt Bayiler'},
        ),
        migrations.AlterModelOptions(
            name='transferlog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bayi Data Transfer Logları'},
        ),
    ]
