# Generated by Django 5.2.10 on 2026-02-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_controller", "0004_revert_encryption_to_plain_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVValidationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(db_index=True, max_length=255)),
                ("row_number", models.IntegerField()),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("HEADER", "Header Hatası"),
                            ("DELIMITER", "Alan Ayracı Hatası"),
                            ("DECIMAL", "Decimal Ayracı Hatası"),
                            ("DATE_FORMAT", "Tarih Formatı Hatası"),
                            ("NUMERIC", "Sayısal Değer Hatası"),
                            ("STATUS", "Status Değeri Hatası"),
                            ("EMPTY_FIELD", "Boş Alan Hatası"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("error_detail", models.TextField()),
                ("raw_row_data", models.TextField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "bayi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="branch_controller.bayi",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["filename", "detected_at"],
                        name="branch_cont_filenam_c75d40_idx",
                    ),
                    models.Index(
                        fields=["error_type", "detected_at"],
                        name="branch_cont_error_t_b3c2ce_idx",
                    ),
                ],
            },
        ),
    ]
