# Generated by Django 5.2.10 on 2026-02-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_controller", "0005_csvvalidationerror"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csvvalidationerror",
            options={
                "ordering": ["-detected_at"],
                "verbose_name": "CSV Validation Özeti",
                "verbose_name_plural": "CSV Validation Özetleri",
            },
        ),
        migrations.RemoveIndex(
            model_name="csvvalidationerror",
            name="branch_cont_filenam_c75d40_idx",
        ),
        migrations.RemoveIndex(
            model_name="csvvalidationerror",
            name="branch_cont_error_t_b3c2ce_idx",
        ),
        # Önce eski alanları sil
        migrations.RemoveField(
            model_name="csvvalidationerror",
            name="error_detail",
        ),
        migrations.RemoveField(
            model_name="csvvalidationerror",
            name="error_type",
        ),
        migrations.RemoveField(
            model_name="csvvalidationerror",
            name="raw_row_data",
        ),
        migrations.RemoveField(
            model_name="csvvalidationerror",
            name="row_number",
        ),
        # Yeni alanları ekle
        migrations.AddField(
            model_name="csvvalidationerror",
            name="accuracy_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Doğruluk oranı (0.00 - 100.00)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="csvvalidationerror",
            name="error_count",
            field=models.IntegerField(default=0, help_text="Toplam hata sayısı"),
        ),
        migrations.AddField(
            model_name="csvvalidationerror",
            name="error_summary",
            field=models.JSONField(
                default=dict, help_text="Hata türlerine göre gruplu detaylar"
            ),
        ),
        migrations.AddField(
            model_name="csvvalidationerror",
            name="summary_message",
            field=models.TextField(
                blank=True, default="", help_text="Formatlanmış özet mesaj"
            ),
        ),
        migrations.AddField(
            model_name="csvvalidationerror",
            name="total_rows",
            field=models.IntegerField(
                default=0, help_text="Toplam satır sayısı (header hariç)"
            ),
        ),
        migrations.AddField(
            model_name="csvvalidationerror",
            name="validation_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="CSV'nin ait olduğu tarih",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="csvvalidationerror",
            index=models.Index(
                fields=["bayi", "validation_date"],
                name="branch_cont_bayi_id_46a362_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="csvvalidationerror",
            index=models.Index(
                fields=["accuracy_rate"], name="branch_cont_accurac_4a6c59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csvvalidationerror",
            index=models.Index(
                fields=["validation_date", "detected_at"],
                name="branch_cont_validat_ff85c9_idx",
            ),
        ),
        # Unique together'ı en son ekle (tüm alanlar hazır olduktan sonra)
        migrations.AlterUniqueTogether(
            name="csvvalidationerror",
            unique_together={("bayi", "filename", "validation_date")},
        ),
    ]
