# Generated by Django 5.2.11 on 2026-03-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_controller', '0008_alter_csvvalidationerror_validation_date'),
        ('branch_controller', '0008_transferlog_signature'),
    ]

    operations = [
    ]
