# Generated by Django 5.2.10 on 2026-02-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("row_count", models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="CSVColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                (
                    "template_value",
                    models.CharField(
                        blank=True,
                        help_text="string için: user{i}@mail.com",
                        max_length=200,
                    ),
                ),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                (
                    "date_format",
                    models.CharField(blank=True, default="%Y-%m-%d", max_length=50),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="csv_generator.csvtemplate",
                    ),
                ),
            ],
        ),
    ]
