# Generated by Django 5.2.10 on 2026-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csv_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CSVJobColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                (
                    "example_value",
                    models.CharField(
                        help_text="Örn: user{i}@mail.com, 25, 2024-01-01",
                        max_length=200,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="csv_generator.csvjob",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CSVColumn",
        ),
        migrations.DeleteModel(
            name="CSVTemplate",
        ),
    ]
